version: '3.8'

services:
  proxy:
    image: proxy
    container_name: proxy
    build:
      dockerfile: .docker/Dockerfile
      context: "."
    command: ['python', '/src/app.py', '--port=9000']
    ports:
     - 9000:9000
